language: python
python:
 - "3.6"
cache: pip
services:
 - postgresql
install:
 - pip install -r requirements.txt
 - pip install coveralls
 - pip install coverage
before_script:
 - psql -c 'create database storotestdb;' -U postgres
script:
 - pytest -v --cov=app
after_script:
 - coveralls 
after_success:
 - coveralls
